[package]
name = "nnsplit"
version = "0.2.2"
authors = ["Benjamin Minixhofer <bminixhofer@gmail.com>"]
edition = "2018"

description = "Rust bindings for fast, robust sentence splitting using machine learning."
repository = "https://github.com/bminixhofer/nnsplit"
homepage = "https://github.com/bminixhofer/nnsplit"
documentation = "https://github.com/bminixhofer/nnsplit"
keywords = ["pytorch", "deep-learning", "machine-learning", "tokenizer", "sentencizer"]
categories = ["science"]
license = "MIT"
readme = "README.md"

include = ["src/*.rs", "tests/*.rs", "build.rs", "data"]

[dependencies]
tch = {version = "0.1.6", optional = true}
ndarray = "0.13"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.3"
quickcheck_macros = "0.9.1"
quickcheck = "0.9.1"
rand = "0.7"

[features]
default = ["tch-rs-backend"]

tch-rs-backend = ["tch"]