[package]
name = "nnsplit_python"
version = "0.1.0"
authors = ["Benjamin Minixhofer <bminixhofer@gmail.com>"]
edition = "2018"

[lib]
name = "nnsplit"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.13"
numpy = {git = "https://github.com/bminixhofer/rust-numpy"}
pyo3 = {git = "https://github.com/PyO3/pyo3", rev = "e6f8fa7"}

[dependencies.nnsplit]
path = "../../nnsplit"
default-features =  false
features = ["model-loader"]

[package.metadata.maturin]
requires-dist = ["torch>=1.4,<2"]