name: Javascript Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    env:
      working-directory: bindings/javascript
    strategy:
      matrix:
        browser: ["firefox", "chrome", "electron"]

    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Build module
        run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Run Cypress tests
        uses: cypress-io/github-action@v1
        with:
          working-directory: ${{env.working-directory}}
          start: npm run start_test_server
          wait-on: 'http://localhost:8080'
          browser: ${{ matrix.browser }}
