name: Python Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: bindings/python
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        make install
      working-directory: ${{env.working-directory}}
    - name: Build
      run: |
        make build
      working-directory: ${{env.working-directory}}
    - name: Test
      run: |
        make test
      working-directory: ${{env.working-directory}}
    - name: Store python version pattern
      run: |
        echo ::set-env name=WHEEL_PATTERN::"*cp`python -c 'import sys; print(str(sys.version_info.major) + str(sys.version_info.minor))'`*.whl"
    - name: Store wheel name
      working-directory: target/wheels
      run: |
        echo ::set-env name=WHEEL_NAME::$(ls ${{env.WHEEL_PATTERN}})
    - name: Upload wheel to nightly Release
      uses: gfreezy/upload-release-asset@v1.0.2 # change this once https://github.com/actions/upload-release-asset/pull/22 is merged
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/bminixhofer/nnsplit/releases/27930194/assets{?name,label} # nightly release
        asset_path: target/wheels/${{env.WHEEL_NAME}}
        release_id: 27930194
        asset_name: ${{env.WHEEL_NAME}}
        asset_content_type: application/zip
