name: Update Nightly Tag

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag Repo
        uses: richardsimko/update-tag@master
        with:
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
